import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styled from 'styled-components';
import Right from '../components/Right';
import Sidebar from '../components/Sidebar';
import { auth } from '../firebase';

export default function Home() {
    const [dark, setDark] = useState(false);
    return (
        <div className="a7a">
            <Head>
                <title>WhatsApp</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <Sidebar />
                <Right />
            </Container>
        </div>
    );
}
const Container = styled.div`
    max-width: 1400px !important;
    margin: 1rem auto;
    display: flex;
    height: calc(100vh - 2rem);
    box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.17);
    backdrop-filter: blur(4px);
    -webkit-backdrop-filter: blur(4px);
    border-radius: 10px;
    border: 1px solid rgba(255, 255, 255, 0.18);
    @media (max-width: 868px) {
        overflow: hidden;
    }
`;
